/*
 * Copyright (c) 2021 - for information on the respective copyright owner
 * see the NOTICE file and/or the repository https://github.com/carbynestack/cli-ng.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package io.carbynestack.testing.command;

import io.carbynestack.cli.util.Format;
import io.carbynestack.cli.util.Verbosity;

/**
 * Represents an aggregation of a command execution test case generated by {@link CommandSource}.
 * The summation comprises the exit code, command output, and encountered errors.
 *
 * @param exitCode  the exit code of the executed command
 * @param out       the output of the executed command
 * @param err       the encountered errors of the executed command
 * @param ansi      is ANSI command output enable
 * @param verbosity the verbosity of the executed command
 * @param format    the format of the executed command output
 * @param filed     the output of the executed command was written to a file
 * @since 0.1.0
 */
public record CommandResult(int exitCode, String out, String err, boolean ansi, Verbosity verbosity,
                            Format format, boolean filed) {
}
